### ISSUE TITLE
Crash-  FATAL EXCEPTION: GLThread 4338 11-30 23:25:44.308: E/AndroidRuntime(11463): java.lang.UnsatisfiedLinkError: 

### ISSUE THREAD

**Issue by alexliubj** [zagayevskiy/Pacman#3]
11-30 23:25:44.198: D/libEGL(11463): loaded /system/lib/egl/libEGL_adreno200.so
11-30 23:25:44.198: D/libEGL(11463): loaded /system/lib/egl/libGLESv1_CM_adreno200.so
11-30 23:25:44.218: D/libEGL(11463): loaded /system/lib/egl/libGLESv2_adreno200.so
11-30 23:25:44.228: I/Adreno200-EGL(11463): <qeglDrvAPI_eglInitialize:269>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB_VANILLA.04.02.02.60.051_msm8960_JB_VANILLA_CL2997615_release_AU (CL2997615)
11-30 23:25:44.228: I/Adreno200-EGL(11463): Build Date: 04/11/13 Thu
11-30 23:25:44.228: I/Adreno200-EGL(11463): Local Branch: 
11-30 23:25:44.228: I/Adreno200-EGL(11463): Remote Branch: quic/mako_jb_mr1
11-30 23:25:44.228: I/Adreno200-EGL(11463): Local Patches: NONE
11-30 23:25:44.228: I/Adreno200-EGL(11463): Reconstruct Branch: AU_LINUX_ANDROID_JB_VANILLA.04.02.02.60.051 +  NOTHING
11-30 23:25:44.248: E/(11463): s3dReadConfigFile:75: Can't open file for reading
11-30 23:25:44.258: E/(11463): s3dReadConfigFile:75: Can't open file for reading
11-30 23:25:44.258: E/(11463): s3dReadConfigFile:75: Can't open file for reading
11-30 23:25:44.268: D/OpenGLRenderer(11463): Enabling debug mode 0
11-30 23:25:44.298: E/(11463): s3dReadConfigFile:75: Can't open file for reading
11-30 23:25:44.298: I/pacman(11463): PacmanView.onSurfaceChanded
11-30 23:25:44.308: W/dalvikvm(11463): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/zagayevskiy/pacman/PacmanLib;
11-30 23:25:44.308: W/dalvikvm(11463): threadid=11: thread exiting with uncaught exception (group=0x414b7700)
11-30 23:25:44.308: E/AndroidRuntime(11463): FATAL EXCEPTION: GLThread 4338
11-30 23:25:44.308: E/AndroidRuntime(11463): java.lang.UnsatisfiedLinkError: Couldn't load pacman from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zagayevskiy.pacman-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.zagayevskiy.pacman-2, /vendor/lib, /system/lib]]]: findLibrary returned null
11-30 23:25:44.308: E/AndroidRuntime(11463):    at java.lang.Runtime.loadLibrary(Runtime.java:355)
11-30 23:25:44.308: E/AndroidRuntime(11463):    at java.lang.System.loadLibrary(System.java:525)
11-30 23:25:44.308: E/AndroidRuntime(11463):    at com.zagayevskiy.pacman.PacmanLib.<clinit>(PacmanLib.java:8)
11-30 23:25:44.308: E/AndroidRuntime(11463):    at com.zagayevskiy.pacman.PacmanView$PacmanRenderer.onSurfaceChanged(PacmanView.java:54)
11-30 23:25:44.308: E/AndroidRuntime(11463):    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1514)
11-30 23:25:44.308: E/AndroidRuntime(11463):    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1242)
11-30 23:25:44.458: I/dalvikvm(11463): Rejecting re-init on previously-failed class Lcom/zagayevskiy/pacman/PacmanLib; v=0x0
11-30 23:25:44.458: D/AndroidRuntime(11463): Shutting down VM
11-30 23:25:44.458: W/dalvikvm(11463): threadid=1: thread exiting with uncaught exception (group=0x414b7700)
11-30 23:25:44.458: I/Process(11463): Sending signal. PID: 11463 SIG: 9

**Comment by zagayevskiy** [comment]
It's known problem because I also see this trace in my Google Play developer console. But I don't know how to fix it. I can't repeat it on my test devices. If you can help fix it, I'll be grateful to you.
